# -*- coding: utf-8 -*-
"""abss net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZ0r1iLbyN0IvPdmXPCBGigKWnJqwi2K
"""

# ============================================================
# FULL CORRECTED COLAB NOTEBOOK
# Reliable and Explainable Deep Learning for
# Diabetic Retinopathy Grading Using Attention-Based
# State Space Networks (ABSS-Net)
#
# DATASET STRUCTURE USED IN THIS NOTEBOOK:
#
# ROOT_DIR/
# ├── train                 # Excel/CSV file (ignored in this notebook)
# └── Train_image/
#     ├── Mild/
#     ├── Moderate/
#     ├── No_DR/
#     ├── Proliferate_DR/
#     ├── Severe/
#     └── export.pkl        # ignored automatically
#
# NOTE:
# - This notebook uses ONLY the folder structure inside Train_image/
# - The 'train' Excel file is not required here
# - Labels are inferred from folder names
# ============================================================

# =========================
# 1. Install dependencies
# =========================
!pip install -q timm torchmetrics scikit-learn opencv-python matplotlib seaborn pandas numpy openpyxl

# =========================
# 2. Imports
# =========================
import os
import random
import math
import shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    cohen_kappa_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.transforms import InterpolationMode

import timm
from torchmetrics.classification import MulticlassCalibrationError

# =========================
# 3. Reproducibility
# =========================
def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

seed_everything(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# =========================
# 4. Mount Google Drive
# =========================
from google.colab import drive
drive.mount('/content/drive')

# =========================
# 5. Paths and configuration
# =========================
# UPDATE THIS ROOT PATH ACCORDING TO YOUR DRIVE LOCATION
# Example:
# /content/drive/MyDrive/DR224
import os

NUM_CLASSES = 5
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 20
LR = 1e-4
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 2
MODEL_SAVE_PATH = "/content/abssnet_best.pth"
HISTORY_SAVE_PATH = "/content/abssnet_training_history.csv"

CLASS_NAMES = ["No_DR", "Mild", "Moderate", "Severe", "Proliferate_DR"]
CLASS_TO_IDX = {cls_name: idx for idx, cls_name in enumerate(CLASS_NAMES)}
IDX_TO_CLASS = {idx: cls_name for cls_name, idx in CLASS_TO_IDX.items()}

ROOT_DIR = None
IMG_DIR = None

for root, dirs, files in os.walk("/content/drive/MyDrive/DR224"):
    if "Train_image" in dirs:
        candidate = os.path.join(root, "Train_image")
        if all(os.path.isdir(os.path.join(candidate, c)) for c in CLASS_NAMES):
            ROOT_DIR = root
            IMG_DIR = candidate
            break

print("Detected ROOT_DIR:", ROOT_DIR)
print("Detected IMG_DIR :", IMG_DIR)

if ROOT_DIR is None or IMG_DIR is None:
    raise FileNotFoundError("Could not find Train_image folder with expected class folders inside /content/drive/MyDrive")

# =========================
# 6. Basic path checks
# =========================
if not os.path.exists(ROOT_DIR):
    raise FileNotFoundError(f"ROOT_DIR not found: {ROOT_DIR}")

if not os.path.exists(IMG_DIR):
    raise FileNotFoundError(f"Train_image folder not found: {IMG_DIR}")

print("\nContents of ROOT_DIR:")
print(os.listdir(ROOT_DIR))

print("\nContents of Train_image:")
print(os.listdir(IMG_DIR))

# =========================
# 7. Transforms
# =========================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE), interpolation=InterpolationMode.BILINEAR),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.10, hue=0.02),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE), interpolation=InterpolationMode.BILINEAR),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

# =========================
# 8. Dataset classes
# =========================
class DRFolderDataset(Dataset):
    def __init__(self, img_dir, class_to_idx, transform=None):
        self.img_dir = img_dir
        self.class_to_idx = class_to_idx
        self.transform = transform
        self.samples = []

        valid_exts = (".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff", ".webp")

        for class_name, class_idx in class_to_idx.items():
            class_folder = os.path.join(img_dir, class_name)

            if not os.path.isdir(class_folder):
                print(f"Warning: folder not found -> {class_folder}")
                continue

            for file_name in os.listdir(class_folder):
                file_path = os.path.join(class_folder, file_name)

                if os.path.isfile(file_path) and file_name.lower().endswith(valid_exts):
                    self.samples.append((file_path, class_idx))

        if len(self.samples) == 0:
            raise ValueError(f"No images found inside {img_dir}. Please check folder names and file extensions.")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        image = Image.open(img_path).convert("RGB")

        if self.transform:
            image = self.transform(image)

        return image, label


class DRSplitDataset(Dataset):
    def __init__(self, samples, transform=None):
        self.samples = samples
        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        image = Image.open(img_path).convert("RGB")

        if self.transform:
            image = self.transform(image)

        return image, label

# =========================
# 9. Build full dataset
# =========================
full_dataset = DRFolderDataset(IMG_DIR, CLASS_TO_IDX, transform=None)
all_samples = full_dataset.samples
all_labels = [label for _, label in all_samples]

print("\nTotal images found:", len(all_samples))

# =========================
# 10. Class distribution
# =========================
full_counts = np.bincount(all_labels, minlength=NUM_CLASSES)

print("\nOverall class distribution:")
for i, c in enumerate(full_counts):
    print(f"{IDX_TO_CLASS[i]}: {c}")

plt.figure(figsize=(8, 4))
plt.bar([IDX_TO_CLASS[i] for i in range(NUM_CLASSES)], full_counts)
plt.title("Overall Class Distribution")
plt.xlabel("Class")
plt.ylabel("Count")
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

# =========================
# 11. Train-validation split
# =========================
train_samples, val_samples = train_test_split(
    all_samples,
    test_size=0.20,
    stratify=all_labels,
    random_state=42
)

train_dataset = DRSplitDataset(train_samples, transform=train_transform)
val_dataset = DRSplitDataset(val_samples, transform=val_transform)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

print("\nTrain samples:", len(train_samples))
print("Val samples  :", len(val_samples))
print("Train batches:", len(train_loader))
print("Val batches  :", len(val_loader))

# =========================
# 12. Split distributions
# =========================
train_labels = [label for _, label in train_samples]
val_labels = [label for _, label in val_samples]

train_counts = np.bincount(train_labels, minlength=NUM_CLASSES)
val_counts = np.bincount(val_labels, minlength=NUM_CLASSES)

print("\nTrain class counts:")
for i, c in enumerate(train_counts):
    print(f"{IDX_TO_CLASS[i]}: {c}")

print("\nVal class counts:")
for i, c in enumerate(val_counts):
    print(f"{IDX_TO_CLASS[i]}: {c}")

# =========================
# 13. Class weights
# =========================
class_weights = 1.0 / np.maximum(train_counts, 1)
class_weights = class_weights / class_weights.sum() * len(class_weights)
class_weights = torch.tensor(class_weights, dtype=torch.float32).to(device)

print("\nClass weights:", class_weights)

# =========================
# 14. Show sample images
# =========================
def denormalize_image(img_tensor):
    img = img_tensor.permute(1, 2, 0).cpu().numpy()
    img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
    img = np.clip(img, 0, 1)
    return img

def show_batch_samples(dataset, num_images=8):
    rows, cols = 2, 4
    fig, axes = plt.subplots(rows, cols, figsize=(14, 7))
    axes = axes.flatten()

    for ax in axes:
        idx = random.randint(0, len(dataset) - 1)
        image, label = dataset[idx]
        img = denormalize_image(image)

        ax.imshow(img)
        ax.set_title(IDX_TO_CLASS[label])
        ax.axis("off")

    plt.tight_layout()
    plt.show()

show_batch_samples(train_dataset)

# =========================
# 15. Attention modules
# =========================
class SEBlock(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        hidden = max(channels // reduction, 8)
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(channels, hidden),
            nn.ReLU(inplace=True),
            nn.Linear(hidden, channels),
            nn.Sigmoid()
        )

    def forward(self, x):
        b, c, _, _ = x.shape
        y = self.pool(x).view(b, c)
        y = self.fc(y).view(b, c, 1, 1)
        return x * y


class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        padding = kernel_size // 2
        self.conv = nn.Conv2d(2, 1, kernel_size=kernel_size, padding=padding, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        y = torch.cat([avg_out, max_out], dim=1)
        y = self.sigmoid(self.conv(y))
        return x * y


class CBAMBlock(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.channel_attn = SEBlock(channels)
        self.spatial_attn = SpatialAttention()

    def forward(self, x):
        x = self.channel_attn(x)
        x = self.spatial_attn(x)
        return x

# =========================
# 16. State space inspired block
# =========================
class StateSpaceBlock(nn.Module):
    def __init__(self, dim, expansion=2, dropout=0.1):
        super().__init__()
        hidden_dim = dim * expansion

        self.norm = nn.LayerNorm(dim)
        self.in_proj = nn.Linear(dim, hidden_dim)
        self.dwconv = nn.Conv1d(hidden_dim, hidden_dim, kernel_size=5, padding=2, groups=hidden_dim)
        self.gate = nn.Linear(dim, hidden_dim)
        self.out_proj = nn.Linear(hidden_dim, dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # x: [B, N, C]
        residual = x
        x_norm = self.norm(x)

        u = self.in_proj(x_norm)              # [B, N, hidden]
        g = torch.sigmoid(self.gate(x_norm))  # [B, N, hidden]

        u = u.transpose(1, 2)                 # [B, hidden, N]
        u = self.dwconv(u)
        u = u.transpose(1, 2)                 # [B, N, hidden]

        x = u * g
        x = self.out_proj(x)
        x = self.dropout(x)

        return x + residual

# =========================
# 17. ABSS-Net model
# =========================
class ABSSNet(nn.Module):
    def __init__(self, num_classes=5, backbone_name="tf_efficientnet_b0_ns", pretrained=True):
        super().__init__()

        self.backbone = timm.create_model(
            backbone_name,
            pretrained=pretrained,
            features_only=True,
            out_indices=(2, 3, 4)
        )

        feature_info = self.backbone.feature_info.channels()
        c3, c4, c5 = feature_info[-3], feature_info[-2], feature_info[-1]

        self.attn3 = CBAMBlock(c3)
        self.attn4 = CBAMBlock(c4)
        self.attn5 = CBAMBlock(c5)

        self.proj3 = nn.Conv2d(c3, 128, kernel_size=1)
        self.proj4 = nn.Conv2d(c4, 128, kernel_size=1)
        self.proj5 = nn.Conv2d(c5, 128, kernel_size=1)

        self.fusion = nn.Conv2d(128 * 3, 256, kernel_size=3, padding=1)
        self.bn = nn.BatchNorm2d(256)
        self.act = nn.GELU()

        self.token_proj = nn.Conv2d(256, 256, kernel_size=1)
        self.ssm1 = StateSpaceBlock(dim=256, expansion=2, dropout=0.1)
        self.ssm2 = StateSpaceBlock(dim=256, expansion=2, dropout=0.1)

        self.cls_head = nn.Sequential(
            nn.LayerNorm(256),
            nn.Linear(256, 128),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes)
        )

        self.conf_head = nn.Sequential(
            nn.LayerNorm(256),
            nn.Linear(256, 64),
            nn.GELU(),
            nn.Linear(64, 1)
        )

    def forward(self, x):
        feats = self.backbone(x)
        f3, f4, f5 = feats[-3], feats[-2], feats[-1]

        f3 = self.attn3(f3)
        f4 = self.attn4(f4)
        f5 = self.attn5(f5)

        f3 = self.proj3(f3)
        f4 = self.proj4(f4)
        f5 = self.proj5(f5)

        target_size = f3.shape[-2:]
        f4 = F.interpolate(f4, size=target_size, mode="bilinear", align_corners=False)
        f5 = F.interpolate(f5, size=target_size, mode="bilinear", align_corners=False)

        fused = torch.cat([f3, f4, f5], dim=1)
        fused = self.act(self.bn(self.fusion(fused)))

        tokens = self.token_proj(fused)
        B, C, H, W = tokens.shape
        tokens = tokens.flatten(2).transpose(1, 2)  # [B, N, C]

        tokens = self.ssm1(tokens)
        tokens = self.ssm2(tokens)

        pooled = tokens.mean(dim=1)

        logits = self.cls_head(pooled)
        confidence = torch.sigmoid(self.conf_head(pooled))

        return logits, confidence

# =========================
# 18. Loss functions
# =========================
class FocalLoss(nn.Module):
    def __init__(self, gamma=2.0, alpha=None):
        super().__init__()
        self.gamma = gamma
        self.alpha = alpha

    def forward(self, logits, targets):
        ce = F.cross_entropy(logits, targets, reduction="none", weight=self.alpha)
        pt = torch.exp(-ce)
        focal = ((1 - pt) ** self.gamma) * ce
        return focal.mean()


def calibration_loss(logits, targets):
    probs = torch.softmax(logits, dim=1)
    true_probs = probs.gather(1, targets.unsqueeze(1)).squeeze(1)
    return torch.mean((true_probs - 1.0) ** 2)

# =========================
# 19. Initialize model
# =========================
model = ABSSNet(num_classes=NUM_CLASSES).to(device)

criterion_focal = FocalLoss(gamma=2.0, alpha=class_weights)

optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

scaler = torch.cuda.amp.GradScaler(enabled=torch.cuda.is_available())
calibration_metric = MulticlassCalibrationError(num_classes=NUM_CLASSES, n_bins=15, norm="l1").to(device)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\nTotal parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")

# =========================
# 20. Train function
# =========================
def train_one_epoch(model, loader, optimizer):
    model.train()
    running_loss = 0.0
    preds_all = []
    labels_all = []

    for images, labels in tqdm(loader, desc="Training", leave=False):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()

        with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):
            logits, confidence = model(images)
            loss_cls = criterion_focal(logits, labels)
            loss_cal = calibration_loss(logits, labels)
            loss = loss_cls + 0.1 * loss_cal

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item() * images.size(0)

        preds = torch.argmax(logits, dim=1)
        preds_all.extend(preds.detach().cpu().numpy())
        labels_all.extend(labels.detach().cpu().numpy())

    epoch_loss = running_loss / len(loader.dataset)
    epoch_acc = accuracy_score(labels_all, preds_all)
    epoch_f1 = f1_score(labels_all, preds_all, average="macro")
    epoch_kappa = cohen_kappa_score(labels_all, preds_all, weights="quadratic")

    return epoch_loss, epoch_acc, epoch_f1, epoch_kappa

# =========================
# 21. Validation function
# =========================
@torch.no_grad()
def validate_one_epoch(model, loader):
    model.eval()
    running_loss = 0.0
    preds_all = []
    labels_all = []
    probs_all = []

    calibration_metric.reset()

    for images, labels in tqdm(loader, desc="Validation", leave=False):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        logits, confidence = model(images)
        loss_cls = criterion_focal(logits, labels)
        loss_cal = calibration_loss(logits, labels)
        loss = loss_cls + 0.1 * loss_cal

        running_loss += loss.item() * images.size(0)

        probs = torch.softmax(logits, dim=1)
        preds = torch.argmax(probs, dim=1)

        calibration_metric.update(probs, labels)

        preds_all.extend(preds.cpu().numpy())
        labels_all.extend(labels.cpu().numpy())
        probs_all.extend(probs.cpu().numpy())

    epoch_loss = running_loss / len(loader.dataset)
    epoch_acc = accuracy_score(labels_all, preds_all)
    epoch_f1 = f1_score(labels_all, preds_all, average="macro")
    epoch_kappa = cohen_kappa_score(labels_all, preds_all, weights="quadratic")
    epoch_ece = calibration_metric.compute().item()

    try:
        epoch_auc = roc_auc_score(labels_all, np.array(probs_all), multi_class="ovr")
    except Exception:
        epoch_auc = 0.0

    return epoch_loss, epoch_acc, epoch_f1, epoch_kappa, epoch_auc, epoch_ece, labels_all, preds_all, probs_all

# =========================
# 22. Training loop
# =========================
history = {
    "train_loss": [],
    "train_acc": [],
    "train_f1": [],
    "train_kappa": [],
    "val_loss": [],
    "val_acc": [],
    "val_f1": [],
    "val_kappa": [],
    "val_auc": [],
    "val_ece": []
}

best_kappa = -1.0

for epoch in range(EPOCHS):
    print(f"\nEpoch [{epoch + 1}/{EPOCHS}]")

    train_loss, train_acc, train_f1, train_kappa = train_one_epoch(model, train_loader, optimizer)
    val_loss, val_acc, val_f1, val_kappa, val_auc, val_ece, y_true, y_pred, y_prob = validate_one_epoch(model, val_loader)

    scheduler.step()

    history["train_loss"].append(train_loss)
    history["train_acc"].append(train_acc)
    history["train_f1"].append(train_f1)
    history["train_kappa"].append(train_kappa)
    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)
    history["val_f1"].append(val_f1)
    history["val_kappa"].append(val_kappa)
    history["val_auc"].append(val_auc)
    history["val_ece"].append(val_ece)

    print(f"Train Loss: {train_loss:.4f} | Acc: {train_acc:.4f} | Macro-F1: {train_f1:.4f} | QWK: {train_kappa:.4f}")
    print(f"Val   Loss: {val_loss:.4f} | Acc: {val_acc:.4f} | Macro-F1: {val_f1:.4f} | QWK: {val_kappa:.4f} | AUC: {val_auc:.4f} | ECE: {val_ece:.4f}")

    if val_kappa > best_kappa:
        best_kappa = val_kappa
        torch.save(model.state_dict(), MODEL_SAVE_PATH)
        print(f"Best model saved to: {MODEL_SAVE_PATH}")

print("\nTraining completed.")

# =========================
# 23. Load best model and final evaluation
# =========================
model.load_state_dict(torch.load(MODEL_SAVE_PATH, map_location=device))
val_loss, val_acc, val_f1, val_kappa, val_auc, val_ece, y_true, y_pred, y_prob = validate_one_epoch(model, val_loader)

print("\nFinal Validation Results")
print(f"Accuracy : {val_acc:.4f}")
print(f"Macro-F1 : {val_f1:.4f}")
print(f"QWK      : {val_kappa:.4f}")
print(f"AUC      : {val_auc:.4f}")
print(f"ECE      : {val_ece:.4f}")

print("\nClassification Report:\n")
print(classification_report(y_true, y_pred, target_names=CLASS_NAMES, digits=4))

# =========================
# 24. Confusion matrix
# =========================
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.tight_layout()
plt.show()

# =========================
# 25. Training curves
# =========================
plt.figure(figsize=(8, 5))
plt.plot(history["train_loss"], label="Train Loss")
plt.plot(history["val_loss"], label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss Curve")
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history["train_kappa"], label="Train QWK")
plt.plot(history["val_kappa"], label="Val QWK")
plt.xlabel("Epoch")
plt.ylabel("QWK")
plt.title("Quadratic Weighted Kappa")
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history["val_auc"], label="Val AUC")
plt.plot(history["val_ece"], label="Val ECE")
plt.xlabel("Epoch")
plt.ylabel("Metric Value")
plt.title("Validation AUC and ECE")
plt.legend()
plt.tight_layout()
plt.show()

# =========================
# 26. Grad-CAM
# =========================
class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None

        self.forward_handle = self.target_layer.register_forward_hook(self.save_activation)
        self.backward_handle = self.target_layer.register_full_backward_hook(self.save_gradient)

    def save_activation(self, module, input, output):
        self.activations = output

    def save_gradient(self, module, grad_input, grad_output):
        self.gradients = grad_output[0]

    def generate(self, input_tensor, class_idx=None):
        self.model.eval()
        logits, _ = self.model(input_tensor)

        if class_idx is None:
            class_idx = logits.argmax(dim=1).item()

        self.model.zero_grad()
        score = logits[:, class_idx]
        score.backward(retain_graph=True)

        gradients = self.gradients
        activations = self.activations

        weights = gradients.mean(dim=(2, 3), keepdim=True)
        cam = (weights * activations).sum(dim=1, keepdim=True)
        cam = F.relu(cam)

        cam = F.interpolate(cam, size=(IMG_SIZE, IMG_SIZE), mode="bilinear", align_corners=False)
        cam = cam.squeeze().detach().cpu().numpy()
        cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

        return cam, class_idx

# =========================
# 27. Grad-CAM visualization
# =========================
inv_normalize = transforms.Normalize(
    mean=[-0.485 / 0.229, -0.456 / 0.224, -0.406 / 0.225],
    std=[1 / 0.229, 1 / 0.224, 1 / 0.225]
)

gradcam = GradCAM(model, model.fusion)

def show_gradcam(dataset, index=0):
    image_tensor, label = dataset[index]
    input_tensor = image_tensor.unsqueeze(0).to(device)

    cam, pred = gradcam.generate(input_tensor)

    img = denormalize_image(image_tensor)

    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.imshow(img)
    plt.title(f"Original\nTrue: {IDX_TO_CLASS[label]}")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(cam, cmap="jet")
    plt.title(f"Grad-CAM\nPred: {IDX_TO_CLASS[pred]}")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(img)
    plt.imshow(cam, cmap="jet", alpha=0.4)
    plt.title("Overlay")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

show_gradcam(val_dataset, index=min(5, len(val_dataset)-1))

# =========================
# 28. Prediction with confidence
# =========================
@torch.no_grad()
def predict_with_confidence(model, dataset, index=0):
    model.eval()
    image_tensor, label = dataset[index]
    input_tensor = image_tensor.unsqueeze(0).to(device)

    logits, confidence = model(input_tensor)
    probs = torch.softmax(logits, dim=1).cpu().numpy()[0]
    pred = np.argmax(probs)
    conf = confidence.item()

    print("True label:", IDX_TO_CLASS[label])
    print("Predicted :", IDX_TO_CLASS[pred])
    print("Class probabilities:")
    for i, p in enumerate(probs):
        print(f"  {IDX_TO_CLASS[i]}: {p:.4f}")
    print("Reliability confidence:", round(conf, 4))

predict_with_confidence(model, val_dataset, index=min(5, len(val_dataset)-1))

# =========================
# 29. Save training history
# =========================
history_df = pd.DataFrame(history)
history_df.to_csv(HISTORY_SAVE_PATH, index=False)
print(f"\nTraining history saved to: {HISTORY_SAVE_PATH}")

# =========================
# 30. Optional: copy files to Drive
# =========================
SAVE_TO_DRIVE = False   # change to True if needed

if SAVE_TO_DRIVE:
    output_dir = os.path.join(ROOT_DIR, "outputs")
    os.makedirs(output_dir, exist_ok=True)

    shutil.copy(MODEL_SAVE_PATH, os.path.join(output_dir, "abssnet_best.pth"))
    shutil.copy(HISTORY_SAVE_PATH, os.path.join(output_dir, "abssnet_training_history.csv"))

    print(f"Files copied to: {output_dir}")

# =========================
# 31. Final message
# =========================
print("\nABSS-Net training and evaluation completed successfully.")
print("Dataset used from folder structure: ROOT_DIR/Train_image/{No_DR, Mild, Moderate, Severe, Proliferate_DR}")
print("The 'train' file and 'export.pkl' are ignored in this notebook.")