"""export_cv_splits.py -- materialise the exact experimental partitions as CSV.

The manuscript partitions are fully deterministic given the image folder, so the
split assignment can be regenerated by any reader without redistributing images:

  * 5-fold protocol : StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
  * dev protocol    : stratified 80/20 train_test_split(random_state=42)

Files are enumerated in sorted order within each class folder so the assignment
is stable across filesystems.

Usage
-----
    python code/export_cv_splits.py \
        --img-dir data/DR224/Train_image \
        --out results/tables/cv_folds.csv

Output columns: filename, class_name, label, cv_fold, dev_split
"""
import argparse
import csv
import os
import sys

CLASS_NAMES = ["No_DR", "Mild", "Moderate", "Severe", "Proliferate_DR"]
EXPECTED = {"No_DR": 1805, "Mild": 370, "Moderate": 999, "Severe": 193, "Proliferate_DR": 295}
SEED = 42
N_SPLITS = 5


def collect(img_dir):
    files, labels = [], []
    for idx, cls in enumerate(CLASS_NAMES):
        d = os.path.join(img_dir, cls)
        if not os.path.isdir(d):
            sys.exit(f"ERROR: missing class folder: {d}")
        names = sorted(f for f in os.listdir(d) if os.path.isfile(os.path.join(d, f)))
        if len(names) != EXPECTED[cls]:
            print(f"  WARNING: {cls}: found {len(names)}, manuscript used {EXPECTED[cls]}")
        files.extend(os.path.join(cls, n) for n in names)
        labels.extend([idx] * len(names))
    return files, labels


def main():
    ap = argparse.ArgumentParser(description="Export the deterministic CV and dev splits.")
    ap.add_argument("--img-dir", required=True, help="Folder containing the five class subfolders.")
    ap.add_argument("--out", default="results/tables/cv_folds.csv", help="Destination CSV.")
    args = ap.parse_args()

    try:
        import numpy as np
        from sklearn.model_selection import StratifiedKFold, train_test_split
    except ImportError:
        sys.exit("ERROR: scikit-learn and numpy are required. pip install -r requirements.txt")

    files, labels = collect(args.img_dir)
    y = np.array(labels)
    print(f"Collected {len(files)} images across {len(CLASS_NAMES)} classes.")

    fold = np.full(len(y), -1, dtype=int)
    skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)
    for k, (_, test_idx) in enumerate(skf.split(np.zeros(len(y)), y)):
        fold[test_idx] = k

    idx = np.arange(len(y))
    tr, va = train_test_split(idx, test_size=0.20, stratify=y, random_state=SEED)
    dev = np.empty(len(y), dtype=object)
    dev[tr] = "train"
    dev[va] = "val"

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["filename", "class_name", "label", "cv_fold", "dev_split"])
        for f, lab, fo, dv in zip(files, labels, fold, dev):
            w.writerow([f, CLASS_NAMES[lab], lab, int(fo), dv])

    print(f"Wrote {args.out}")
    print("Per-fold held-out counts:", {int(k): int((fold == k).sum()) for k in range(N_SPLITS)})
    print("Dev split counts        :", {"train": int((dev == 'train').sum()), "val": int((dev == 'val').sum())})


if __name__ == "__main__":
    main()
