"""frequency_attenuation_analysis.py  --  Reviewer 2 (Comment 1), Reviewer 1 (Comment 7)

Quantifies the high-spatial-frequency energy attenuated by Ben-Graham filtering,
per DR grade, to turn the "Gaussian filtering attenuates lesions" claim from
qualitative into quantitative. Computes the fraction of spectral energy above a
radial cut-off and the mean gradient magnitude. Runs on DR224 alone to profile
the filtered domain; if RAW_IMG_DIR is provided it contrasts raw vs filtered.
"""
import argparse
import os
import cv2
import numpy as np
from PIL import Image


def high_freq_ratio(gray, cutoff=0.25):
    F = np.fft.fftshift(np.fft.fft2(gray.astype(np.float32)))
    power = np.abs(F) ** 2
    h, w = gray.shape; cy, cx = h / 2, w / 2
    Y, X = np.ogrid[:h, :w]
    r = np.sqrt((Y - cy) ** 2 + (X - cx) ** 2) / np.sqrt(cy ** 2 + cx ** 2)
    return float(power[r > cutoff].sum() / (power.sum() + 1e-12))


def grad_mag(gray):
    """Mean gradient magnitude using the unnormalised 3x3 OpenCV Sobel operator.

    IMPORTANT (2026-07-20): this previously used ``np.gradient`` (central
    difference), which is ~6-8x smaller in scale than the ``cv2.Sobel`` operator
    used by ``abss_net_all_experiments_colab.py`` -- the pipeline that produced
    the gradient-magnitude column reported in the manuscript. The two
    implementations are now aligned so a re-run reproduces the manuscript scale.
    The archived CSV in results/tables/ still holds the OLD np.gradient values
    and must be regenerated by re-running this script. See REPRODUCIBILITY.md
    section C.
    """
    gx = cv2.Sobel(gray.astype(np.float32), cv2.CV_32F, 1, 0)
    gy = cv2.Sobel(gray.astype(np.float32), cv2.CV_32F, 0, 1)
    return float(np.mean(np.sqrt(gx ** 2 + gy ** 2)))


def profile_dir(img_dir, classes=("No_DR", "Mild", "Moderate", "Severe", "Proliferate_DR")):
    out = {}
    for c in classes:
        d = os.path.join(img_dir, c)
        if not os.path.isdir(d):
            continue
        hf, gm = [], []
        for fn in os.listdir(d):
            g = np.array(Image.open(os.path.join(d, fn)).convert("L"))
            hf.append(high_freq_ratio(g)); gm.append(grad_mag(g))
        out[c] = (float(np.mean(hf)), float(np.mean(gm)))
        print(f"{c:16s} HF-ratio={out[c][0]:.4f}  grad-mag={out[c][1]:.2f}  (n={len(hf)})")
    return out


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Profile high-frequency energy by DR class.")
    parser.add_argument("--img-dir", required=True, help="Image root with class subfolders.")
    parser.add_argument("--raw-img-dir", default=None, help="Optional raw APTOS root with matching class subfolders.")
    args = parser.parse_args()

    filt = profile_dir(args.img_dir)
    if args.raw_img_dir:
        raw = profile_dir(args.raw_img_dir)
        print("\nPer-grade high-frequency attenuation: 1 - filtered/raw")
        for c in filt:
            if c in raw and raw[c][0] != 0:
                print(f"{c:16s} attenuation={1 - filt[c][0] / raw[c][0]:.4f}")
